# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moovie

	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'Kingfisher', '~> 4.10.0'
	pod 'RxSwift', '~> 4'
        pod 'RxCocoa', '~> 4'


  target 'MoovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
